FROM docker.io/caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/desec \
    --with github.com/caddyserver/certmagic@v0.25.4 \
    --with github.com/mholt/caddy-ratelimit

FROM docker.io/caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
